### ISSUE TITLE
the vendor publish is not working properly

### ISSUE THREAD

**Issue by bhagat-abhishek** [coderflexx/laravisit#37]
php artisan vendor:publish --provider="Coderflex\Laravisit\LaravisitServiceProvider"

INFO No publishable resources for tag [].

-- When i run the vendor:publish

i get the below error and i am not able to run the migrate command from installing it.

![image](https://user-images.githubusercontent.com/85464874/226771603-68aaf6c5-59df-4a43-8616-c8a3dc632e35.png)

**Comment by amerhany** [comment]
> php artisan vendor:publish --provider="Coderflex\Laravisit\LaravisitServiceProvider"
> 
> INFO No publishable resources for tag [].
> 
> -- When i run the vendor:publish
> 
> i get the below error and i am not able to run the migrate command from installing it.
> 
> ![image](https://user-images.githubusercontent.com/85464874/226771603-68aaf6c5-59df-4a43-8616-c8a3dc632e35.png)

Same problem

**Comment by ousid** [comment]
@amerhany @bhagat-abhishek 

I just created a fresh Laravel project with the package installed, and I found no issues.
![image](https://user-images.githubusercontent.com/21012933/228402629-f80269cb-0969-4d6e-a14e-6c8298b4176b.png)

Could you provide more info, with your Laravel version, and which version are you using in this package?

**Comment by ousid** [comment]
Closing the issue for now, feel free to reopen it, once having more info.
