### ISSUE TITLE
php artisan vendor:publish --provider="Coderflex\\Laravisit\\LaravisitServiceProvider"

### ISSUE THREAD

**Issue by madfortech** [coderflexx/laravisit#51]
![Capture-1](https://github.com/coderflexx/laravisit/assets/21261716/d6265a81-7edc-422a-8b05-f4a3fc3ec3d5)

![Capture-2](https://github.com/coderflexx/laravisit/assets/21261716/4f2f080d-9ad4-49cb-a4f4-6e89582cf50f)

My php version PHP 8.1.17
Laravel version  10.32.1

   INFO  No publishable resources for tag [].
   
   Help me

**Comment by nakir00** [comment]
i have exactly the same problem

**Comment by nakir00** [comment]
i resolved it manually.

I started by retrieving the migration into Vendor and copied its contents

![image](https://github.com/coderflexx/laravisit/assets/105824977/98043fa9-d371-4d7d-8996-bfdf0cd9e876)

Then I created a migration, pasted the copied content into it, and then migrated

![image](https://github.com/coderflexx/laravisit/assets/105824977/a49d5514-90b7-4d07-9fb3-5ccc02df0a99)

Then I copied the config file and pasted it into my project file

![image](https://github.com/coderflexx/laravisit/assets/105824977/f36f68cb-f481-4895-83e0-bb4f3dad09c9)
![image](https://github.com/coderflexx/laravisit/assets/105824977/6630c8c5-e87c-4e11-b855-6b4cecdc7902)

And it worked for me

![image](https://github.com/coderflexx/laravisit/assets/105824977/3b5f8b99-75fb-47a4-a87a-77e8b7f7aad9)
